{% set version = "0.41.0" %}

package:
  name: u8darts
  version: {{ version }}

source:
  git_url: https://github.com/unit8co/darts
  git_rev: {{ version }}

build:
  number: 0
  noarch: python

outputs:
  - name: u8darts
    build:
      noarch: python
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - pip
      run:
        - python >={{ python_min }}
        - holidays >=0.11.1
        - joblib >=0.16.0
        - matplotlib-base >=3.3.0
        - narwhals >=1.25.1
        - nfoursid >=1.0.0
        - numpy >=2.2.0
        - pandas >=2.2.0
        - pyod >=0.9.5
        - requests >=2.22.0
        - scikit-learn >=1.6.0,<1.8.0
        - scipy >=1.3.2
        - shap >=0.40.0
        - statsmodels >=0.14.0
        - tqdm >=4.60.0
        - typing-extensions>=4.0.0
        - xarray >=0.17.0
    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_model
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.encoders
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.utils
        - darts.utils.data
        - darts.utils.data.tabularization
        - darts.utils.data.torch_datasets
        - darts.utils.historical_forecasts
        - darts.utils.likelihood_models
      source_files:
        - darts
      commands:
        - pytest darts/tests -k "not test_fit_predict_determinism and not test_fit_predict_randomized"
      requires:
        - python {{ python_min }}
        - pip
        - testfixtures
        - pytest

  - name: u8darts-notorch
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("u8darts", exact=True) }}
        - catboost >=1.0.6
        - lightgbm >=3.2.0
        - prophet >=1.1.1
        - statsforecast >=1.4.0
        - xgboost >=2.1.4

    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_model
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.encoders
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.utils
        - darts.utils.data
        - darts.utils.data.tabularization
        - darts.utils.data.torch_datasets
        - darts.utils.historical_forecasts
        - darts.utils.likelihood_models
      source_files:
        - darts
      commands:
        - pytest darts/tests -k "not test_fit_predict_determinism and not test_fit_predict_randomized"
      requires:
        - python {{ python_min }}
        - pip
        - testfixtures
        - pytest

  - name: u8darts-torch
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("u8darts", exact=True) }}
        - pytorch-lightning >=1.5.0,<2.5.3
        - tensorboardx >=2.1
        - pytorch >=2.0.0
        - huggingface_hub >=0.35.3
        - safetensors >=0.6.2

    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_model
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.encoders
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.utils
        - darts.utils.data
        - darts.utils.data.tabularization
        - darts.utils.data.torch_datasets
        - darts.utils.historical_forecasts
        - darts.utils.likelihood_models
      source_files:
        - darts
      commands:
        - pytest darts/tests -k "not test_fit_predict_determinism and not test_fit_predict_randomized" --ignore=darts/tests/models/forecasting/test_chronos2.py --ignore=darts/tests/models/forecasting/test_foundation.py
      requires:
        - python {{ python_min }}
        - pip
        - testfixtures
        - pytest

  - name: u8darts-all
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("u8darts", exact=True) }}
        - pytorch-lightning >=2.0.0,<2.5.3
        - tensorboardx >=2.1
        - pytorch >=2.0.0
        - huggingface_hub >=0.35.3
        - safetensors >=0.6.2
        - catboost >=1.0.6
        - lightgbm >=3.2.0
        - prophet >=1.1.1
        - statsforecast >=1.4.0
        - xgboost >=2.1.4

    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_model
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.encoders
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.utils
        - darts.utils.data
        - darts.utils.data.tabularization
        - darts.utils.data.torch_datasets
        - darts.utils.historical_forecasts
        - darts.utils.likelihood_models
      source_files:
        - darts
      commands:
        - pytest darts/tests -k "not test_fit_predict_determinism and not test_fit_predict_randomized" --ignore=darts/tests/models/forecasting/test_chronos2.py --ignore=darts/tests/models/forecasting/test_foundation.py
      requires:
        - python {{ python_min }}
        - pip
        - testfixtures
        - pytest

about:
  home: https://unit8co.github.io/darts/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A python library for user-friendly forecasting and anomaly detection on time series.
  dev_url: https://github.com/unit8co/darts
  doc_url: https://unit8co.github.io/darts/

extra:
  recipe-maintainers:
    - dennisbader
